# Generated by Django 2.1.5 on 2019-10-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
    ]
